# Generated by Django 4.1.3 on 2022-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='photos/persons')),
                ('stock', models.CharField(default='SOME STRING', max_length=140)),
                ('code', models.CharField(default='SOME STRING', max_length=140)),
                ('barcode', models.CharField(default='SOME STRING', max_length=140)),
                ('price', models.DecimalField(decimal_places=5.0, max_digits=6)),
            ],
        ),
    ]
