# Generated by Django 4.1.3 on 2022-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.DecimalField(decimal_places=5, default=5.0, max_digits=6),
        ),
    ]
